# pi assumed 3.14159
aoi:
  top:
    entity_name: top_aoi_plane
    description: "Top AOI plane for roof-mounted sensors "

    # Plane geometry (local to plane)
    size:
      width: 0.8
      depth: 0.8

    # World pose (copied from Gazebo UI)
    pose:
      x: 0.1
      y: 0.0
      z: 1.29
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

    visual:
      color: [0.10, 0.25, 0.85, 0.60]

    grid:
      rows: 4
      cols: 4


  front:
    entity_name: front_aoi_plane
    description: "Front AOI plane for forward-facing sensors "

    # Rectangle facing forward
    size:
      width: 0.3
      depth: 1

    # World pose (copied from Gazebo UI)
    pose:
      x: 1.25
      y: 0.0
      z: 0.62
      roll: 0.0
      pitch: 1.57
      yaw: 0.0

    visual:
      color: [0.95, 0.80, 0.10, 0.60]

    grid:
      rows: 3
      cols: 2

  # left:
  #   entity_name: left_aoi_plane
  #   description: "Left side AOI plane for lateral sensors"

  #   # Vertical plane on the left side of the train
  #   size:
  #     width: 1
  #     depth: 1

  #   # World pose (relative to train)
  #   pose:
  #     x: 0.0
  #     y: 0.6        # left side (positive Y)
  #     z: 0.7        # mid-height of train body
  #     roll: 0.0
  #     pitch: 1.57   # vertical plane
  #     yaw: 1.57     # facing left

  #   visual:
  #     color: [0.8, 0.2, 0.2, 0.4]

  #   grid:
  #     rows: 2
  #     cols: 2


  right:
    entity_name: right_aoi_plane
    description: "Right side AOI plane for lateral sensors"

    # Vertical plane on the right side of the train
    size:
      width: 0.5
      depth: 1

    # World pose (relative to train)
    pose:
      x: 0.0
      y: -0.5       # right side (negative Y)
      z: 0.7        # mid-height of train body
      roll: 0.0
      pitch: 1.57   # vertical plane
      yaw: -1.57    # facing right

    visual:
      color: [1.0, 1.0, 1.0, 0.4]

    grid:
      rows: 2
      cols: 5