# pi assumed 3.14159

# (Optional legacy, no longer used by aoi_spawn2)
train_spawn:
  x: 0.0
  y: -0.018
  z: 0.1
  R: 0.0
  P: 0.0
  Y: 1.571


aoi:
  top:
    entity_name: top_aoi_plane
    description: "Top AOI plane for roof-mounted sensors "

    # Plane geometry (local to plane)
    size:
      width: 0.8
      depth: 0.8

    # World pose (copied from Gazebo UI)
    pose:
      x: 0.0
      y: 0.0
      z: 1.75
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

    visual:
      color: [0.2, 0.8, 0.2, 0.4]

    grid:
      rows: 3
      cols: 3


  front:
    entity_name: front_aoi_plane
    description: "Front AOI plane for forward-facing sensors "

    # Rectangle facing forward
    size:
      width: 0.4
      depth: 1

    # World pose (copied from Gazebo UI)
    pose:
      x: 1.0
      y: 0.0
      z: 0.4
      roll: 0.0
      pitch: 1.57
      yaw: 0.0

    visual:
      color: [0.2, 0.2, 0.8, 0.4]

    grid:
      rows: 3
      cols: 3

  left:
    entity_name: left_aoi_plane
    description: "Left side AOI plane for lateral sensors"

    # Vertical plane on the left side of the train
    size:
      width: 1
      depth: 1

    # World pose (relative to train)
    pose:
      x: 0.0
      y: 0.6        # left side (positive Y)
      z: 0.7        # mid-height of train body
      roll: 0.0
      pitch: 1.57   # vertical plane
      yaw: 1.57     # facing left

    visual:
      color: [0.8, 0.2, 0.2, 0.4]

    grid:
      rows: 3
      cols: 3


  right:
    entity_name: right_aoi_plane
    description: "Right side AOI plane for lateral sensors"

    # Vertical plane on the right side of the train
    size:
      width: 1
      depth: 1

    # World pose (relative to train)
    pose:
      x: 0.0
      y: -0.5       # right side (negative Y)
      z: 0.7        # mid-height of train body
      roll: 0.0
      pitch: 1.57   # vertical plane
      yaw: -1.57    # facing right

    visual:
      color: [0.8, 0.8, 0.2, 0.4]

    grid:
      rows: 3
      cols: 3