slots:
- name: top_aoi_plane_r0_c0
  aoi: top_aoi_plane
  grid:
    row: 0
    col: 0
  pose:
    x: -0.131764
    y: -0.048636
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  sensor: null
- name: top_aoi_plane_r0_c1
  aoi: top_aoi_plane
  grid:
    row: 0
    col: 1
  pose:
    x: -0.051364
    y: -0.231764
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  sensor: null
- name: top_aoi_plane_r1_c0
  aoi: top_aoi_plane
  grid:
    row: 1
    col: 0
  pose:
    x: 0.051364
    y: 0.031764
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  sensor: null
- name: top_aoi_plane_r1_c1
  aoi: top_aoi_plane
  grid:
    row: 1
    col: 1
  pose:
    x: 0.131764
    y: -0.151364
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  sensor: null
